### ISSUE TITLE
ActionView::Template::Error: undefined method `user_groups_enabled?' for #<Decidim::Organization:0x00007f3c8b51fc60>

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#416]
https://sentry.io/open-source-politics/decidim-steamroll/issues/846824457/?referrer=github_plugin

```
NoMethodError: undefined method `user_groups_enabled?' for #<Decidim::Organization:0x00007f3c8b51fc60>
Did you mean?  users_registration_mode?
  active_model/attribute_methods.rb:430:in `method_missing'
    match ? attribute_missing(match, *args, &block) : super
  decidim/proposals/application_helper.rb:143:in `filter_origin_values'
    base += [["user_group", t("decidim.proposals.application_helper.filter_origin_values.user_groups")]] if current_organization.user_groups_enabled?
  .bundle/ruby/2.5.0/bundler/gems/decidim-0b52fbc0f06d/decidim-proposals/app/views/decidim/proposals/proposals/_filters.html.erb:19:in `block in __bundle_ruby_______bundler_gems_decidim__b__fbc_f__d_decidim_proposals_app_views_decidim_proposals_proposals__filters_html_erb___2920862384889024939_69948996604520'
    <%= form.collection_radio_buttons :origin, filter_origin_values, :first, :last, legend_title: t(".origin") %>
  decidim/filters_helper.rb:17:in `block (2 levels) in filter_form_for'
    yield form
  action_view/helpers/capture_helper.rb:41:in `block in capture'
    buffer = with_output_buffer { value = yield(*args) }
...
(184 additional frame(s) were not displayed)

ActionView::Template::Error: undefined method `user_groups_enabled?' for #<Decidim::Organization:0x00007f3c8b51fc60>
Did you mean?  users_registration_mode?

ActionView::Template::Error: undefined method `user_groups_enabled?' for #<Decidim::Organization:0x00007f3c8b51fc60>
Did you mean?  users_registration_mode?
```

**Comment by armandfardeau** [comment]
Fixed by https://github.com/OpenSourcePolitics/decidim/pull/402
