### ISSUE TITLE
NameError: uninitialized constant Decidim::Admin::UnhideResource

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#609]
https://sentry.io/organizations/open-source-politics/issues/988835696/?project=1235134&referrer=github_plugin

```
NameError: uninitialized constant Decidim::Admin::UnhideResource
Did you mean?  Decidim::Admin::HideResource
  decidim/admin/moderations_controller.rb:48:in `unhide'
    Admin::UnhideResource.call(reportable, current_user) do
  action_controller/metal/basic_implicit_render.rb:6:in `send_action'
    super.tap { default_render unless performed? }
  abstract_controller/base.rb:194:in `process_action'
    send_action(method_name, *args)
  action_controller/metal/rendering.rb:30:in `process_action'
    super
  abstract_controller/callbacks.rb:42:in `block in process_action'
    super
...
(135 additional frame(s) were not displayed)

NameError: uninitialized constant Decidim::Admin::UnhideResource
Did you mean?  Decidim::Admin::HideResource
```

**Comment by lu-hamani** [comment]
Bug triggered when trying to unhide a reported proposal from here : 
https://dev.steamroll.osp.cat/admin/participatory_processes/alias-accusantium/moderations?hidden=true
Another bug is triggered with this action => #608
