### ISSUE TITLE
NotImplementedError: NotImplementedError

### ISSUE THREAD

**Issue by armandfardeau** [OpenSourcePolitics/decidim#610]
https://sentry.io/organizations/open-source-politics/issues/988829860/?project=1235134&referrer=github_plugin

```
NotImplementedError: NotImplementedError
  decidim/reportable.rb:43:in `reported_content_url'
    raise NotImplementedError
  decidim/reported_mailer.rb:34:in `reported_content_url'
    @reported_content_url ||= @report.moderation.reportable.reported_content_url
  abstract_controller/helpers.rb:67:in `reported_content_url'
    controller.send(%(#{meth}), *args, &blk)             #   controller.send(:current_user, *args, &blk)
  .bundle/ruby/2.5.0/bundler/gems/decidim-42586d637aad/decidim-core/app/views/decidim/reported_mailer/report.html.erb:4:in `__bundle_ruby_______bundler_gems_decidim______d___aad_decidim_core_app_views_decidim_reported_mailer_report_html_erb__460808807165676505_47073375657720'
    <%= t(".report_html", { url: reported_content_url }) %>
  action_view/template.rb:159:in `block in render'
    view.send(method_name, locals, buffer, &block)
...
(128 additional frame(s) were not displayed)

NotImplementedError
```

**Comment by lu-hamani** [comment]
Bug triggered when trying to access the hidden collaborative draft from the link provided here : 
https://dev.steamroll.osp.cat/admin/participatory_processes/alias-accusantium/moderations?hidden=true

**Comment by lu-hamani** [comment]
A backport was supposed to fix this one => https://github.com/OpenSourcePolitics/decidim/pull/590
